CREATE DATABASE EMERGENCYSYSTEM;
USE EMERGENCYSYSTEM;
CREATE TABLE PATIENTS(
PATIENT_ID INT,
PATIENT_NO INT UNIQUE,
SSN INT UNIQUE,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
GENDER VARCHAR(1),
BIRTH_DATE DATE,
PHONE VARCHAR(20),
BLOODTYPE VARCHAR(5),
ADDRESS TEXT,
ALLERGIES TEXT,
MEDICAL_HISTORY TEXT,
PRIMARY KEY(PATIENT_ID)
);
CREATE TABLE DOCTORS(
DOCTOR_ID INT,
SSN INT UNIQUE,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
GENDER VARCHAR(1),
BIRTHDATE DATE,
SPECIALTY VARCHAR(50),
DEGREE VARCHAR(50),
PHONE VARCHAR(50),
EMAIL VARCHAR(100) UNIQUE,
JOIN_DATE DATE,
PRIMARY KEY(DOCTOR_ID)
);
CREATE TABLE INVESTIGATING(
DOCTOR_ID INT,
PATIENT_ID INT,
INVESTIGATING_DATE DATE,
HOURS_PER_WEEK FLOAT,
NOTES TEXT,
PRIMARY KEY(DOCTOR_ID, PATIENT_ID)
);
CREATE TABLE NURSES(
NURSE_ID INT,
SSN INT UNIQUE,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
GENDER VARCHAR(1),
BIRTHDATE DATE,
PHONE VARCHAR(20),
EMAIL VARCHAR(100) UNIQUE,
SHIFT_TYPE VARCHAR(50),
PRIMARY KEY(NURSE_ID)
);
CREATE TABLE ROOMS(
ROOM_ID INT,
ROOM_NO INT UNIQUE,
ROOM_TYPE VARCHAR(50),
PATIENT_ID INT,
CAPACITY VARCHAR(50),
AVAILABILITY_STATUS VARCHAR(1),
PRIMARY KEY(ROOM_ID)
);
CREATE TABLE AMBULANCES(
AMBULANCE_ID INT,
AMBULANCE_NO INT UNIQUE,
DRIVER_NAME VARCHAR(100),
AMBULANCE_STATUS VARCHAR(50),
GPS_LOCATION TEXT,
PHONE VARCHAR(20),
PRIMARY KEY(AMBULANCE_ID)
);
CREATE TABLE EMERGENCY_CASES(
CASE_ID INT,
PATIENT_ID INT,
DOCTOR_ID INT,
AMBULANCE_ID INT,
ARRIVAL_TIME TIME,
DISCHARGE_TIME TIME,
TRIAGE_LEVEL VARCHAR(1),
ARRIVAL_METHOD VARCHAR(50),
CASE_STATUS TEXT,
SYMPTOMS TEXT,
DIAGNOSIS VARCHAR(100),
NOTES TEXT,
HEART_RATE VARCHAR(50),
TEMP VARCHAR(50),
BP VARCHAR(50),
DATE_ISSUED DATE,
PRIMARY KEY(CASE_ID)
);
CREATE TABLE NURSES_PARTICIPATION(
NURSE_ID INT,
CASE_ID INT,
ASSIGNMENT_TIME TIME,
NOTES TEXT,
PRIMARY KEY(CASE_ID, NURSE_ID)
);
CREATE TABLE PAYMENTS(
PAYMENT_ID INT,
PATIENT_ID INT,
AMOUNT FLOAT,
PAYMENT_METHOD VARCHAR(1),
PAYMENT_STATUS VARCHAR(50),
PAYMENT_DATE DATE,
INSURANCE_PROVIDOR VARCHAR(100),
TRANSACTION_REFRENCES VARCHAR(50),
PRIMARY KEY(PAYMENT_ID)
);
CREATE TABLE PRESCRIPTIONS(
PRESCRIPTION_ID INT,
PATIENT_ID INT,
DOCTOR_ID INT,
PRESCRIPTION_DATE DATE,
NOTES TEXT,
PRIMARY KEY(PRESCRIPTION_ID)
);
CREATE TABLE MEDICATIONS(
MEDICATION_ID INT,
MEDICATION_NAME VARCHAR(100),
MEDICATION_DESCRIPTION TEXT,
SIDE_EFFECTS TEXT,
PRIMARY KEY (MEDICATION_ID)
);
CREATE TABLE PRESCRIPTION_DETAILS(
PRESCRIPTION_ID INT,
MEDICATION_ID INT,
DOSAGE VARCHAR(50),
FREQUANCY VARCHAR(50),
START_DATE DATE,
END_DATE DATE,
DIRECTIONS TEXT,
PRIMARY KEY(PRESCRIPTION_ID, MEDICATION_ID)
);

ALTER TABLE INVESTIGATING
ADD FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID),
ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID);
ALTER TABLE EMERGENCY_CASES
ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
ADD FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID),
ADD FOREIGN KEY(AMBULANCE_ID) REFERENCES AMBULANCES(AMBULANCE_ID);
ALTER TABLE NURSES_PARTICIPATION
ADD FOREIGN KEY(NURSE_ID) REFERENCES NURSES(NURSE_ID),
ADD FOREIGN KEY(CASE_ID) REFERENCES EMERGENCY_CASES(CASE_ID);
ALTER TABLE PRESCRIPTIONS
ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
ADD FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID);
ALTER TABLE ROOMS
ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID);
ALTER TABLE PAYMENTS
ADD FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID);
