DELIMITER //

CREATE TRIGGER after_patient_admission
AFTER INSERT ON EMERGENCY_CASES
FOR EACH ROW
BEGIN
    UPDATE ROOMS
    SET AVAILABILITY_STATUS = 'O' 
    WHERE ROOM_ID = NEW.ROOM_ID;
END //

DELIMITER ;

DELIMITER //

CREATE TRIGGER after_patient_discharge
AFTER UPDATE ON EMERGENCY_CASES
FOR EACH ROW
BEGIN
    IF NEW.DISCHARGE_TIME IS NOT NULL THEN
        UPDATE ROOMS 
        SET AVAILABILITY_STATUS = 'A' 
        WHERE ROOM_ID = NEW.ROOM_ID;
    END IF;
END //

DELIMITER ;

